name: Docker Image CI

on:
  push:
    branches: [ master ]
    paths:
      - 'alpine/rs-run.Dockerfile'
  pull_request:
    branches: [ master ]
    paths:
      - 'alpine/rs-run.Dockerfile'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: check out code
      - uses: mr-smithers-excellent/docker-build-push@v3
        name: Build & push faiss Dev docker image
        with:
          image: gensmusic/alpine-rs-run
          tag: 3.12.0
          registry: docker.io
          dockerfile: alpine/rs-run.Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
