name: FFmpeg runtime deps

on:
  push:
    branches: [ master ]
    paths:
      - ffmpeg/runtime-deps-slim-debian.Dockerfile
  pull_request:
    branches: [ master ]
    paths:
      - ffmpeg/runtime-deps-slim-debian.Dockerfile
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: check out code
      - uses: mr-smithers-excellent/docker-build-push@v3
        name: Build & push Debian FFmpeg docker image
        with:
          image: gensmusic/ffmpeg
          tag: debian-runtime-deps-slim
          registry: docker.io
          dockerfile: ffmpeg/runtime-deps-slim-debian.Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
