name: Docker Image CI

on:
  push:
    branches: [ master ]
    paths:
      - ffmpeg/deps-ubuntu.Dockerfile
  pull_request:
    branches: [ master ]
    paths:
      - ffmpeg/deps-ubuntu.Dockerfile
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: check out code
      - uses: mr-smithers-excellent/docker-build-push@v3
        name: Build & push ubuntu FFmpeg docker image
        with:
          image: gensmusic/ffmpeg
          tag: ubuntu-deps
          registry: docker.io
          dockerfile: ffmpeg/deps-ubuntu.Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
