name: Docker Image CI

on:
  push:
    branches: [ master ]
    paths:
      - 'faiss/official.Dockerfile'
  pull_request:
    branches: [ master ]
    paths:
      - 'faiss/official.Dockerfile'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: check out code

      - uses: mr-smithers-excellent/docker-build-push@v3
        name: Build & push rust faiss official base
        with:
          image: gensmusic/faiss-official
          tag: base
          registry: docker.io
          dockerfile: faiss/faiss-rs.Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}