name: Docker Image CI

on:
  push:
    branches: [ master ]
    paths:
      - 'rust/thirdparty/mosquitto-deps.Dockerfile'
  pull_request:
    branches: [ master ]
    paths:
      - 'rust/thirdparty/mosquitto-deps.Dockerfile'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: check out code
      - uses: mr-smithers-excellent/docker-build-push@v3
        name: Build & push mosquitto Dev docker image
        with:
          image: gensmusic/mosquitto-deps
          tag: 2.0.4
          registry: docker.io
          dockerfile: rust/thirdparty/mosquitto-deps.Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
